from __future__ import annotations

import json
from pathlib import Path


NOTEBOOK = Path("projects/sh2026/workshop/05_affect_and_events.ipynb")
FALLBACK = Path("projects/sh2026/demo/affect_transformer_teaching_fallback_v1.json")


def _source_text(cell: dict) -> str:
    source = cell.get("source", "")
    return "".join(source) if isinstance(source, list) else str(source)


def _set_source(cell: dict, text: str) -> None:
    if isinstance(cell.get("source"), list):
        cell["source"] = text.splitlines(keepends=True)
    else:
        cell["source"] = text


def main() -> None:
    if not FALLBACK.exists():
        raise SystemExit(f"Missing required fallback: {FALLBACK}")

    notebook = json.loads(NOTEBOOK.read_text(encoding="utf-8"))
    changed = 0

    for cell in notebook.get("cells", []):
        text = _source_text(cell)

        if (
            cell.get("cell_type") == "markdown"
            and "## 4. Optional contextual classifiers" in text
            and "Release versions will include precomputed fallback outputs" in text
        ):
            _set_source(
                cell,
                "## 4. Optional contextual classifiers\n\n"
                "If you have a suitable runtime and want a live comparison, switch `FAST_MODE = False`.\n\n"
                "The default workshop path does **not** download transformer models. Instead it loads a precomputed output generated by the same pinned transformer condition used in the SH2026 affect experiment. The file records the exact model names, Hugging Face revisions, generation commit and original teaching passages. It is a reliability fallback, not a benchmark result.\n\n"
                "When `FAST_MODE = False`, the notebook runs those same pinned models live so participants can compare the live and precomputed routes."
            )
            changed += 1

        if (
            cell.get("cell_type") == "code"
            and "if not FAST_MODE:" in text
            and "hf_sent = SentimentAnalyzer" in text
            and "hf_emo = EmotionAnalyzer" in text
        ):
            _set_source(
                cell,
                "fallback_path = repo_dir / \"projects\" / \"sh2026\" / \"demo\" / \"affect_transformer_teaching_fallback_v1.json\"\n"
                "\n"
                "if not FAST_MODE:\n"
                "    subprocess.run([sys.executable, \"-m\", \"pip\", \"install\", \"-q\", \"-r\", \"requirements-transformers.txt\"], check=True)\n"
                "    from spatio_textual.affect_transformer import classify_affect_transformer\n"
                "    transformer_rows = [\n"
                "        {\"segment_id\": i, \"text\": text, **classify_affect_transformer(text)}\n"
                "        for i, text in enumerate(segments)\n"
                "    ]\n"
                "    transformer_source = \"live pinned transformer run\"\n"
                "else:\n"
                "    fallback = json.loads(fallback_path.read_text(encoding=\"utf-8\"))\n"
                "    transformer_rows = fallback[\"records\"]\n"
                "    assert [row[\"text\"] for row in transformer_rows] == segments\n"
                "    transformer_source = \"precomputed pinned transformer fallback\"\n"
                "\n"
                "comparison_rows = []\n"
                "for i, (text, hf) in enumerate(zip(segments, transformer_rows)):\n"
                "    comparison_rows.append({\n"
                "        \"segment\": i,\n"
                "        \"text\": text,\n"
                "        \"rule_sentiment\": sent_results[i][\"label\"],\n"
                "        \"transformer_sentiment\": hf[\"sentiment_label\"],\n"
                "        \"rule_emotion\": emo_results[i][\"label\"],\n"
                "        \"transformer_emotions\": hf[\"emotion_labels\"],\n"
                "    })\n"
                "\n"
                "display(pd.DataFrame(comparison_rows))\n"
                "print(\"Transformer source:\", transformer_source)\n"
                "if FAST_MODE:\n"
                "    print(\"Pinned revisions:\", fallback[\"sentiment_revision\"], fallback[\"emotion_revision\"])"
            )
            changed += 1

    if changed != 2:
        raise SystemExit(f"Expected to update 2 Notebook 05 cells, updated {changed}")

    NOTEBOOK.write_text(json.dumps(notebook, indent=1, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"Updated {NOTEBOOK}")


if __name__ == "__main__":
    main()
